name: Deploy no Kubernetes
on: 
    repository_dispatch:
      types: [remote-deploy]
    workflow_call: 
        inputs:
            manifests:
                type: string
                required: true
                description: "Arquivos de manifesto que serão alterados"
            images:
                type: string
                required: true
                description: "Imagens que são alteradas no manifesto"
            repository:
              type: string
              required: true
              description: "Repositório com os Manifestos"
            ref:
              type: string
              required: true
              description: "Branch do repositorio"
        secrets:
          kubeconfig:
            required: true
            description: "Kubeconfig para configurar o contexto Kubernetes"
jobs:
    deploy-k8s:
        runs-on: ubuntu-latest
        steps: 
        - name: Verificação dos Inputs
          run: |
              echo "${{ toJson(inputs) }}"
              
        - name: Obtendo o código
          uses: actions/checkout@v4.1.5
          with: 
            repository: ${{ inputs.repository }}
            ref: 'main'
        - name: Configuração de contexto do Kubernetes
          uses: azure/k8s-set-context@v4.0.0
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.kubeconfig || secrets.K8S_CONFIG }}
        - name: Execução do Manifesto
          uses: Azure/k8s-deploy@v5
          with:
            manifests: ${{ inputs.manifests}}
            images: ${{ inputs.images}}
